### ISSUE TITLE
Could you please create a docker image for linux/arm64/v8 or share the Docker recipe?

### ISSUE THREAD

**Issue by cmorenoserrano** [yangboz/sgfutils#2]
Hi there!

I'm trying to use sgfutils, but I get an error when compiling the source coude with Make and when I tried your docker image, it's not compatible with the M1 chip in my Mac. Would you be able to create a docker image for linux/arm64/v8 or share the Docker recipe so that I can create my own docker image?

Thank you so much in advance!
Carlos

**Comment by yangboz** [comment]
thanks for your interesting. I will have a try at first.

**Comment by yangboz** [comment]
maybe  it is here: https://stackoverflow.com/questions/66504379/how-to-run-dockerfile-at-silicon-mac-m1-from-intel-mac @cmorenoserrano

**Comment by cmorenoserrano** [comment]
Could you please share your Dockerfile with me so that I can add the FROM --platform=linux/arm64 <image name> to it and see if it works?

**Comment by yangboz** [comment]
sorry the Dockerile only verified many years ago  with my MBA , now I have my M1 testing  on the way.

**Comment by yangboz** [comment]
> --platform=linux/arm64

the Dockerfile is right there https://github.com/yangboz/sgfutils/blob/master/Dockerfile

**Comment by cmorenoserrano** [comment]
Yes, I saw that, but the issue was with the yum image in the recipe, which is not for arm64.
I'm closing this issue because a reddit user (ggPeti) helped me to repackage sgfutils for arm64 and it works now for me.

Thank you very much for the swift communication and willingness to help.

**Comment by yangboz** [comment]
plesse comments it in the source code of Dockerfile? thanks.
